apiVersion: v1
kind: Service
metadata:
  name: whatsit-image-index-bigquery
  namespace: whatsit
  labels:
    name: whatsit-image-index-bigquery
spec:
  type: LoadBalancer
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    name: whatsit-image-index-bigquery
